version: "3"

services:
  release_tracker:
    build: .
    environment:
      CREDENTIALS_GITHUB_TOKEN: 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
      INTERVAL_SECONDS: "43200"

    volumes:
      - "./config/software.json:/app/software.json"
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.2.0-ubuntu
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - "./prometheus_datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml"
      - "./releases-dashboard.json:/etc/grafana/provisioning/dashboards/releases-dashboard.json"
      - "./releases-dashboard.yaml:/etc/grafana/provisioning/dashboards/releases-dashboard.yaml"
    ports:
      - '3000:3000'
volumes:
  prometheus_data: {}